[package]
name = "chemistru-modelling"
version = "0.1.0"
edition = "2021"

[dependencies]
chemistru-elements-api = { git = "https://github.com/Ross-Morgan/chemistru-elements-api" }
petgraph = "0.6.4"
